url: https://jekyll-theme-mnc.michaelnordmeyer.com
title: Your awesome title
author:
  name: Your name
  email: you@example.com
  bio: Your medium-long bio, which, if present, goes into the footer to give the reader an idea of who you are or what you do or what the site is about.
description: > # This means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
tumblelog_title: Tumblelog # Should mimic title in tumblelog.md
tumblelog_description: Short-form posts with little text and/or image- or video-only.
icon: # default: empty, favicon.ico won't be requested b/c of inline data

exclude: [404.md, CODE_OF_CONDUCT.md, History.markdown, jekyll-theme-mnc*, LICENSE.txt, Rakefile.rb, README.md, repo-card.png, screenshot.png, script]
include: [.well-known]
show_excerpts: false # set to true to show excerpts on the homepage
timezone: UTC # default: local timezone

title_separator: " | "

# Theme settings
# https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll#customizing-your-themes-css
# https://github.com/jekyll/minima#customizing-templates
#theme: jekyll-theme-mnc
#remote_theme: michaelnordmeyer/jekyll-theme-mnc
jekyll-theme-mnc:
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%Y-%m-%d"
  category_slug: "category"
  reading-speed: 180 # To calculate reading time. Default is 180 words per minute

  # Minima skin selection.
  # Available skins are:
  # classic            Default, light color scheme.
  # dark               Dark variant of the classic skin.
  # auto               Adaptive skin based on the default classic and dark skins.
  # solarized-light    Light variant of solarized color scheme.
  # solarized-dark     Dark variant of solarized color scheme.
  # solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

  # Generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: jekyll
    # xing: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the pages in order as they should show up
  header_pages:
    - about.md
    - tumblelog.md

# Build settings
#theme: jekyll-theme-mnc

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

## Plugin jekyll-redirect-from settings
redirect_from:
  json: false
